function [z_load, Nf_load, z_unload, Nf_unload] = load_force_curve(filename)
    % Loads a force curve made of load and unload parts from a file 
    % generated by AIST-NT software in 'txt' format. 
    % x (z) values are treated as 'nm' and y (Nf) values as 'au'.
    % ----
    % Arguments:
    % filename = name of the file which contains the curve to load 
    %
    % Returns:
    % z_load = vector containing the z coordinates of the load curve
    % Nf_load = vector containing the Nf coordinates of the load curve
    % z_unload = vector containing the z coordinates of the unload curve
    % Nf_unload = vector containing the Nf coordinates of the unload curve
    
    %{
    % Open the file in order to read from it
    fid = fopen(filename, 'r');

    % Read and discard the first line (which contains 
    fgetl(fid);

    % Read the file as numbers and place them in a vector
    data = fscanf(fid, '%f');

    % Close the file
    fclose(fid);

    % Create a 2 column matrix
    data = reshape(data, 2, []).';
    %}

    data = load(filename);

    % Obtain z and Nf coordinates (the first column is for z)
    z = data(:,1);
    Nf = data(:,2);
    
    % Differ between load and unload curve (the first half is the load
    % curve)
    z_load = z(1:end/2);
    Nf_load = Nf(1:end/2);

    z_unload = z((end/2+1):end);
    Nf_unload = Nf((end/2+1):end);
end