% -------------------------------------------------------------------
%  Generated by MATLAB on 1-Dec-2024 15:19:09
%  MATLAB version: 24.1.0.2689473 (R2024a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('media1.mat');

data = saveVarsMat.data; % <801x2 double> too many elements

clear saveVarsMat;
